-- Level 4: Text objects (BEGINNER tier)
-- Focus: iw, aw, i", i(, ip combined with operators d/c/y
-- Cursor starts at line 1, col 1 of setup_text on challenge load.

return {
  {
    id = "l4_001",
    level = 4,
    description = "Delete the word 'error' using diw. Cursor is on the word.",
    hint1 = "Use 'd' + 'iw' (inner word) to delete the word under the cursor.",
    hint2 = "Type: diw — deletes the word without the surrounding space.",
    setup_text = "error",
    goal_text = "",
    optimal_keystrokes = 3,
  },
  {
    id = "l4_002",
    level = 4,
    description = "Delete the word 'bug' and the trailing space using daw. Cursor is on the word.",
    hint1 = "Use 'daw' (a word) to delete the word and a surrounding space.",
    hint2 = "Type: daw — removes 'bug ' leaving 'fixed'.",
    setup_text = "bug fixed",
    goal_text = "fixed",
    optimal_keystrokes = 3,
  },
  {
    id = "l4_003",
    level = 4,
    description = "Change the text inside the double quotes to 'vim'. Cursor is on the opening quote.",
    hint1 = "Use 'ci\"' (change inner quote) to replace the quoted text.",
    hint2 = "Type: ci\"vim\27 — replaces content inside quotes, then Esc.",
    setup_text = '"hello"',
    goal_text = '"vim"',
    optimal_keystrokes = 8,
  },
  {
    id = "l4_004",
    level = 4,
    description = "Delete the text inside the parentheses. Cursor is on the opening paren.",
    hint1 = "Use 'di(' (delete inner paren) to remove content between ( and ).",
    hint2 = "Type: di( — deletes everything inside the parentheses.",
    setup_text = "(remove me)",
    goal_text = "()",
    optimal_keystrokes = 3,
  },
  {
    id = "l4_005",
    level = 4,
    description = "Yank the inner paragraph. Cursor is on the first line of the paragraph.",
    hint1 = "Use 'yip' (yank inner paragraph) to copy the whole paragraph.",
    hint2 = "Type: yip — yanks the paragraph without surrounding blank lines.",
    setup_text = "first line\nsecond line\nthird line",
    goal_text = "first line\nsecond line\nthird line",
    optimal_keystrokes = 3,
  },
  {
    id = "l4_006",
    level = 4,
    description = "Change the text inside the parentheses to 'x'. Cursor is on the opening paren.",
    hint1 = "Use 'ci(' (change inner paren) to replace content inside parentheses.",
    hint2 = "Type: ci(x\27 — replaces inner content with 'x', then Esc.",
    setup_text = "(old value)",
    goal_text = "(x)",
    optimal_keystrokes = 6,
  },
  {
    id = "l4_007",
    level = 4,
    description = "Delete the inner word 'TODO' leaving just the surrounding text. Cursor is on 'TODO'.",
    hint1 = "Use 'diw' to delete the word under the cursor.",
    hint2 = "Type: diw — removes 'TODO' leaving '[ ]'.",
    setup_text = "[TODO]",
    goal_text = "[]",
    optimal_keystrokes = 4,
  },
  {
    id = "l4_008",
    level = 4,
    description = "Change the quoted string 'world' to 'vim'. Cursor is on the opening quote.",
    hint1 = "Position on the quote and use ci\" to replace the quoted content.",
    hint2 = "Type: ci\"vim\27 — enters insert replacing inner quote content.",
    setup_text = '"world"',
    goal_text = '"vim"',
    optimal_keystrokes = 8,
  },
}
