-- Level 7: Substitution — :s/pat/rep/, :%s/pat/rep/g, basic regex (. * ^ $ \w)
-- Tier: intermediate (no required_keys, no max_keystrokes)

return {
  {
    id = "l7_global_replace",
    level = 7,
    description = "Replace every occurrence of 'foo' with 'bar' in the buffer.",
    hint1 = "Use the global substitution command :%s/foo/bar/g",
    hint2 = "Type: :%s/foo/bar/g<CR>",
    setup_text = "foo is not bar\nfoo again\nanother foo here",
    goal_text  = "bar is not bar\nbar again\nanother bar here",
    optimal_keystrokes = 14,
  },
  {
    id = "l7_first_occurrence_line",
    level = 7,
    description = "Replace only the first 'error' on the current line with 'warn'.",
    hint1 = "Use :s without the g flag to replace only the first match on the line.",
    hint2 = "Type: :s/error/warn/<CR>",
    setup_text = "error: something went wrong, error logged",
    goal_text  = "warn: something went wrong, error logged",
    optimal_keystrokes = 13,
  },
  {
    id = "l7_delete_blank_lines",
    level = 7,
    description = "Delete all blank lines in the buffer.",
    hint1 = "Use :g with pattern ^$ to match empty lines, then d to delete.",
    hint2 = "Type: :g/^$/d<CR>",
    setup_text = "first line\n\nsecond line\n\nthird line\n\n",
    goal_text  = "first line\nsecond line\nthird line",
    optimal_keystrokes = 10,
  },
  {
    id = "l7_replace_word_boundary",
    level = 7,
    description = "Replace 'cat' with 'dog' everywhere in the buffer using a global substitution.",
    hint1 = ":%s will substitute across every line; add /g for all occurrences per line.",
    hint2 = "Type: :%s/cat/dog/g<CR>",
    setup_text = "the cat sat on the mat\na cat is a cat",
    goal_text  = "the dog sat on the mat\na dog is a dog",
    optimal_keystrokes = 14,
  },
  {
    id = "l7_strip_trailing_spaces",
    level = 7,
    description = "Remove all trailing whitespace from every line.",
    hint1 = "Use :%s with a pattern that matches spaces at end of line ($).",
    hint2 = "Type: :%s/ \\+$//<CR>  (one or more spaces before end-of-line, replace with nothing)",
    setup_text = "hello   \nworld  \nvim   ",
    goal_text  = "hello\nworld\nvim",
    optimal_keystrokes = 14,
  },
  {
    id = "l7_replace_any_digit",
    level = 7,
    description = "Replace all digit characters with '#' using \\d (or [0-9]) in a global substitution.",
    hint1 = "Use :%s with \\d to match any digit character.",
    hint2 = "Type: :%s/\\d/#/g<CR>",
    setup_text = "order 42 ships in 3 days\nref: 007",
    goal_text  = "order ## ships in # days\nref: ###",
    optimal_keystrokes = 14,
  },
  {
    id = "l7_anchor_start_of_line",
    level = 7,
    description = "Add '> ' to the beginning of every line (quote-style prefix).",
    hint1 = "Use ^ to anchor the substitution to the start of each line.",
    hint2 = "Type: :%s/^/> /<CR>",
    setup_text = "first\nsecond\nthird",
    goal_text  = "> first\n> second\n> third",
    optimal_keystrokes = 12,
  },
}
