-- Level 6: Search (INTERMEDIATE tier)
-- Focus: /, n/N, *, #, f/t/;/,
-- No required_keys (intermediate = outcome-based grading)
-- No max_keystrokes

return {
  {
    id = "l6_001",
    level = 6,
    description = "Find 'TODO' and delete that entire line.",
    hint1 = "Search with /TODO then use dd to delete the line.",
    hint2 = "Type: /TODO<Enter>dd",
    setup_text = "keep this\nTODO: remove this line\nkeep this too",
    goal_text = "keep this\nkeep this too",
    optimal_keystrokes = 10,
  },
  {
    id = "l6_002",
    level = 6,
    description = "Use f to jump to the '(' on the current line and delete it with x.",
    hint1 = "f( jumps forward to the next '(' character on the line.",
    hint2 = "Type: f(x",
    setup_text = "call foo(args)",
    goal_text = "call fooargs)",
    optimal_keystrokes = 3,
  },
  {
    id = "l6_003",
    level = 6,
    description = "Search for 'error', change it to 'warning'. Only one occurrence.",
    hint1 = "Search /error<Enter> then use cw to change the word.",
    hint2 = "Type: /error<Enter>cwwarning<Esc>",
    setup_text = "log: error occurred",
    goal_text = "log: warning occurred",
    optimal_keystrokes = 16,
  },
  {
    id = "l6_004",
    level = 6,
    description = "Use * to search for the word under cursor, then jump to next match and delete that line.",
    hint1 = "* searches for the exact word under cursor. n jumps to next match.",
    hint2 = "Type: *ndd (search current word, next match, delete line)",
    setup_text = "target line\nsome other line\ntarget line",
    goal_text = "target line\nsome other line",
    optimal_keystrokes = 4,
  },
  {
    id = "l6_005",
    level = 6,
    description = "Use t to jump just before ':' and delete the rest of the line.",
    hint1 = "t: positions cursor just before the ':' character.",
    hint2 = "Type: t:D",
    setup_text = "prefix: delete this",
    goal_text = "prefix:",
    optimal_keystrokes = 3,
  },
  {
    id = "l6_006",
    level = 6,
    description = "Find all lines with 'debug', navigate to second match and delete that line.",
    hint1 = "/debug<Enter> finds first. n jumps to next.",
    hint2 = "Type: /debug<Enter>ndd",
    setup_text = "debug: one\nkeep this\ndebug: two\nkeep that",
    goal_text = "debug: one\nkeep this\nkeep that",
    optimal_keystrokes = 11,
  },
  {
    id = "l6_007",
    level = 6,
    description = "Use ; to repeat the last f-motion and delete the character found.",
    hint1 = "; repeats the last f/t/F/T motion.",
    hint2 = "Type: fx;x — find first x, repeat to next x, delete it.",
    setup_text = "axbxcx",
    goal_text = "axbcx",
    optimal_keystrokes = 4,
  },
}
