-- Level 5: Operator + motion combos (BEGINNER tier)
-- Focus: dw, db, d$, C, cw, ciw, ya(, D, etc. — thinking in vim verbs

return {
  {
    id = "l5_001",
    level = 5,
    description = "Delete from cursor to end of line using D.",
    hint1 = "D = d$ — deletes from cursor to end of line.",
    hint2 = "Type: D",
    setup_text = "keep this: delete from here",
    goal_text = "keep this:",
    optimal_keystrokes = 11,
  },
  {
    id = "l5_002",
    level = 5,
    description = "Change the word 'wrong' to 'right' using cw. Cursor is on 'wrong'.",
    hint1 = "cw deletes the word forward and enters insert mode.",
    hint2 = "Type: cwright\27",
    setup_text = "wrong answer",
    goal_text = "right answer",
    optimal_keystrokes = 8,
  },
  {
    id = "l5_003",
    level = 5,
    description = "Delete 3 words starting from 'one'. Cursor is on 'one'.",
    hint1 = "Use a count with dw: 3dw deletes 3 words.",
    hint2 = "Type: 3dw",
    setup_text = "one two three keep",
    goal_text = "keep",
    optimal_keystrokes = 3,
  },
  {
    id = "l5_004",
    level = 5,
    description = "Change from cursor to end of line to 'done'. Cursor is at 'f' in 'fix me'.",
    hint1 = "C = c$ — changes to end of line and enters insert.",
    hint2 = "Type: Cdone\27",
    setup_text = "done: fix me",
    goal_text = "done: done",
    optimal_keystrokes = 12,
  },
  {
    id = "l5_005",
    level = 5,
    description = "Yank a word including surrounding parens using ya(. Cursor is inside parens, then paste below.",
    hint1 = "ya( yanks the paren block including the parens themselves.",
    hint2 = "Type: ya(p — yanks a( then pastes it after.",
    setup_text = "(hello)",
    goal_text = "(hello)(hello)",
    optimal_keystrokes = 4,
  },
  {
    id = "l5_006",
    level = 5,
    description = "Delete a word backwards using db. Cursor is at end of 'remove'.",
    hint1 = "db deletes backward to start of word.",
    hint2 = "Type: edb — jump to end of word then delete backward.",
    setup_text = "keep remove",
    goal_text = "keep ",
    optimal_keystrokes = 3,
  },
  {
    id = "l5_007",
    level = 5,
    description = "Change the inner word 'old' to 'new' using ciw. Cursor is on 'old'.",
    hint1 = "ciw deletes the word under cursor and enters insert.",
    hint2 = "Type: ciwnew\27",
    setup_text = "value: old",
    goal_text = "value: new",
    optimal_keystrokes = 14,
  },
  {
    id = "l5_008",
    level = 5,
    description = "Delete to end of word using de. Cursor is on 'd' of 'delete'.",
    hint1 = "de deletes to end of current word.",
    hint2 = "Type: de",
    setup_text = "delete this",
    goal_text = " this",
    optimal_keystrokes = 2,
  },
}
