-- Level 8: Marks, Registers, Macros — ma/`a, "a, q{x}...q, @{x}
-- Tier: intermediate (no required_keys, no max_keystrokes)

return {
  {
    id = "l8_set_and_jump_mark",
    level = 8,
    description = "Mark line 1 with 'a', move to line 4, then jump back to mark 'a'.",
    hint1 = "Use 'ma' to set mark a, then navigate away and use '`a' to return.",
    hint2 = "On line 1: ma  then  4G  then  `a  — cursor returns to line 1.",
    setup_text = "mark this line\nline two\nline three\nline four",
    goal_text  = "mark this line\nline two\nline three\nline four",
    optimal_keystrokes = 6,
  },
  {
    id = "l8_yank_to_named_register",
    level = 8,
    description = "Yank the word 'secret' into register 'a', then paste it at the end of line 2.",
    hint1 = "Use \"ayiw to yank the word under cursor into register a, then move and \"ap to paste.",
    hint2 = "Position cursor on 'secret': \"ayiw  then  2G$  then  a<Space>  then  <Esc>\"ap",
    setup_text = "secret\npaste here:",
    goal_text  = "secret\npaste here: secret",
    optimal_keystrokes = 12,
  },
  {
    id = "l8_macro_add_semicolon",
    level = 8,
    description = "Record a macro in register 'q' that appends a semicolon to the current line, then replay it on 3 lines.",
    hint1 = "Use qq to start recording, A; then <Esc> to append semicolon, then q to stop. Use @q to replay.",
    hint2 = "qq A;<Esc> q  then move to next line and  @q  repeat for each line",
    setup_text = "let x = 1\nlet y = 2\nlet z = 3",
    goal_text  = "let x = 1;\nlet y = 2;\nlet z = 3;",
    optimal_keystrokes = 15,
  },
  {
    id = "l8_delete_to_register",
    level = 8,
    description = "Delete the word 'REMOVE' into register 'b', then paste it after 'result:'.",
    hint1 = "Use \"bdaw to delete the word into register b, then navigate and \"bp to paste.",
    hint2 = "Cursor on REMOVE: \"bdaw  then move after 'result:'  then  \"bp",
    setup_text = "REMOVE\nresult:",
    goal_text  = "result: REMOVE",
    optimal_keystrokes = 12,
  },
  {
    id = "l8_macro_with_count",
    level = 8,
    description = "Record a macro to delete the first word of a line, then run it on 4 lines using a count.",
    hint1 = "Record: qq dw q  then move to first target line and use  4@q  to run 4 times.",
    hint2 = "qq dw q  then position on line 2  then  4@q",
    setup_text = "keep: line one\ndelete line one\ndelete line two\ndelete line three\ndelete line four",
    goal_text  = "keep: line one\nline one\nline two\nline three\nline four",
    optimal_keystrokes = 14,
  },
  {
    id = "l8_append_register_yank",
    level = 8,
    description = "Yank line 1 into register 'a' and line 2 into register 'b', then paste both after line 3.",
    hint1 = "Use \"ayy on line 1 to yank into a, \"byy on line 2 to yank into b, then paste at end.",
    hint2 = "1G \"ayy  then  2G \"byy  then  3G \"ap \"bp",
    setup_text = "alpha\nbeta\n---",
    goal_text  = "alpha\nbeta\n---\nalpha\nbeta",
    optimal_keystrokes = 14,
  },
  {
    id = "l8_repeat_macro_replay",
    level = 8,
    description = "Record a macro to uppercase the first character of a line (use ~), then apply it to all 5 lines.",
    hint1 = "Record qq then ~ to toggle case on the first char, then j to move down, then q. Replay with 4@q.",
    hint2 = "1G qq ~j q  then  4@q  to apply to remaining 4 lines",
    setup_text = "apple\nbanana\ncherry\ndate\nelder",
    goal_text  = "Apple\nBanana\nCherry\nDate\nElder",
    optimal_keystrokes = 12,
  },
}
