-- Level 10: Windows, Folds, Neovim-specific — :split/:vsplit/:wincmd, zf/zc/zo/zd, complex regex
-- Tier: advanced (no required_keys, HAS max_keystrokes)

return {
  {
    id = "l10_vsplit_and_switch",
    level = 10,
    description = "Open a vertical split and move focus to the new window.",
    hint1 = "Use :vsplit to create a vertical split; Ctrl-w l (or :wincmd l) moves focus right.",
    hint2 = "Type: :vsplit<CR>  then  <C-w>l  — creates split and moves to it (8 keystrokes)",
    setup_text = "-- edit me in a split",
    goal_text  = "-- edit me in a split",
    max_keystrokes = 12,
    optimal_keystrokes = 8,
  },
  {
    id = "l10_fold_visual_range",
    level = 10,
    description = "Fold lines 2 through 5 using visual selection and zf.",
    hint1 = "Enter visual line mode on line 2, extend to line 5, then press zf to create a fold.",
    hint2 = "2G V 3j zf  — selects lines 2-5 in visual line mode then folds them",
    setup_text = "header\nfold me\nfold me too\nalso fold\nfold this\nfooter",
    goal_text  = "header\nfold me\nfold me too\nalso fold\nfold this\nfooter",
    max_keystrokes = 8,
    optimal_keystrokes = 6,
  },
  {
    id = "l10_complex_regex_capture",
    level = 10,
    description = "Reformat 'YYYY-MM-DD' dates to 'DD/MM/YYYY' using a capture-group substitution.",
    hint1 = "Use \\v with three capture groups for year, month, day; reorder in replacement as \\3/\\2/\\1.",
    hint2 = "Type: :%s/\\v(\\d{4})-(\\d{2})-(\\d{2})/\\3\\/\\2\\/\\1/g<CR>",
    setup_text = "event: 2024-03-15\ndeadline: 2025-12-01",
    goal_text  = "event: 15/03/2024\ndeadline: 01/12/2025",
    max_keystrokes = 36,
    optimal_keystrokes = 30,
  },
  {
    id = "l10_wincmd_cycle",
    level = 10,
    description = "Open a horizontal split, then close it and return to the original window.",
    hint1 = "Use :split to create a horizontal split, then :close (or <C-w>c) to close it.",
    hint2 = ":split<CR>  then  :close<CR>  — opens then closes the split (14 keystrokes)",
    setup_text = "-- single window buffer",
    goal_text  = "-- single window buffer",
    max_keystrokes = 18,
    optimal_keystrokes = 14,
  },
  {
    id = "l10_substitute_multiword_boundary",
    level = 10,
    description = "Replace whole-word 'log' (not 'logger' or 'dialog') with 'print' everywhere.",
    hint1 = "Use \\< and \\> word-boundary anchors in your substitution pattern.",
    hint2 = "Type: :%s/\\<log\\>/print/g<CR>",
    setup_text = "log this\nlogger.info\ndialog box\nlog again",
    goal_text  = "print this\nlogger.info\ndialog box\nprint again",
    max_keystrokes = 22,
    optimal_keystrokes = 18,
  },
  {
    id = "l10_fold_open_close",
    level = 10,
    description = "Close the open fold on the current line with zc, then reopen it with zo.",
    hint1 = "zc closes a fold under the cursor; zo opens it again.",
    hint2 = "Position cursor on a folded block: zc to close, zo to open",
    setup_text = "-- unfold me\nline a\nline b\nline c",
    goal_text  = "-- unfold me\nline a\nline b\nline c",
    max_keystrokes = 6,
    optimal_keystrokes = 4,
  },
}
