-- Level 9: Efficiency Patterns — . repeat, counts, :norm, :g/pat/cmd, \v very-magic, capture groups
-- Tier: advanced (no required_keys, HAS max_keystrokes)

return {
  {
    id = "l9_dot_repeat_semicolons",
    level = 9,
    description = "Append a semicolon to each of the 5 lines using the . repeat command.",
    hint1 = "Fix line 1 with A;<Esc>, then move down and use . to repeat on each remaining line.",
    hint2 = "A;<Esc> j. j. j. j.  — 5 semicolons with 10 keystrokes",
    setup_text = "const a = 1\nconst b = 2\nconst c = 3\nconst d = 4\nconst e = 5",
    goal_text  = "const a = 1;\nconst b = 2;\nconst c = 3;\nconst d = 4;\nconst e = 5;",
    max_keystrokes = 15,
    optimal_keystrokes = 10,
  },
  {
    id = "l9_count_delete_words",
    level = 9,
    description = "Delete the first 4 words of the line in a single command.",
    hint1 = "Combine a count with the dw motion: 4dw deletes 4 words.",
    hint2 = "Type: 4dw<CR>  — deletes 4 words at once",
    setup_text = "remove these four words keep this",
    goal_text  = "keep this",
    max_keystrokes = 6,
    optimal_keystrokes = 3,
  },
  {
    id = "l9_g_delete_debug_lines",
    level = 9,
    description = "Delete all lines containing the word 'debug' using :g.",
    hint1 = "Use :g/pattern/d to delete every line matching the pattern.",
    hint2 = "Type: :g/debug/d<CR>",
    setup_text = "start app\ndebug: init\nmain loop\ndebug: tick\nshutdown",
    goal_text  = "start app\nmain loop\nshutdown",
    max_keystrokes = 14,
    optimal_keystrokes = 11,
  },
  {
    id = "l9_norm_add_prefix",
    level = 9,
    description = "Use :norm to prepend '# ' to lines 2 through 4.",
    hint1 = "Use :2,4norm to run a normal-mode command on a range of lines.",
    hint2 = "Type: :2,4norm I# <CR>  — inserts '# ' at the start of each line in range",
    setup_text = "title\nfirst\nsecond\nthird\nfooter",
    goal_text  = "title\n# first\n# second\n# third\nfooter",
    max_keystrokes = 16,
    optimal_keystrokes = 13,
  },
  {
    id = "l9_verymagic_swap_words",
    level = 9,
    description = "Use \\v very-magic regex to swap 'first' and 'last' on every line.",
    hint1 = "\\v enables very-magic mode where grouping uses () without backslashes.",
    hint2 = "Type: :%s/\\v(first) (last)/\\2 \\1/g<CR>",
    setup_text = "first last\nfirst last again\nno match here",
    goal_text  = "last first\nlast first again\nno match here",
    max_keystrokes = 26,
    optimal_keystrokes = 22,
  },
  {
    id = "l9_count_jump_lines",
    level = 9,
    description = "Move the cursor down exactly 6 lines in one command.",
    hint1 = "Prefix j with a count to jump multiple lines at once.",
    hint2 = "Type: 6j",
    setup_text = "line 1\nline 2\nline 3\nline 4\nline 5\nline 6\nline 7",
    goal_text  = "line 1\nline 2\nline 3\nline 4\nline 5\nline 6\nline 7",
    max_keystrokes = 5,
    optimal_keystrokes = 2,
  },
  {
    id = "l9_g_collect_todos",
    level = 9,
    description = "Delete all lines NOT containing 'TODO' (keep only TODO lines) using :v.",
    hint1 = ":v/pattern/d is the inverse of :g — it acts on lines that do NOT match.",
    hint2 = "Type: :v/TODO/d<CR>",
    setup_text = "init code\nTODO: fix bug\nsome logic\nTODO: add tests\ncleanup",
    goal_text  = "TODO: fix bug\nTODO: add tests",
    max_keystrokes = 13,
    optimal_keystrokes = 10,
  },
}
